# Generated by Django 3.0.6 on 2020-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_description',
            field=models.CharField(max_length=160),
        ),
    ]
