# Generated by Django 3.0.6 on 2020-06-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200613_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_approved',
        ),
    ]
